name: CI

on: [push, pull_request]

jobs:

  lints:
    name: "Lint and typecheck"
    runs-on: ubuntu-latest
    steps:
    - uses: rwjblue/setup-volta@v1
      with:
        node-version: '14'
    - name: "Global yarn"
      run: volta install yarn
    - name: Find yarn cache
      id: yarn-cache-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Lint cardhost
      run: yarn lint
      working-directory: cardhost

  cardhost_tests:
    name: "Cardhost tests"
    runs-on: ubuntu-latest
    steps:
    - uses: rwjblue/setup-volta@v1
      with:
        node-version: '14'
    - name: "Global yarn"
      run: volta install yarn
    - name: Find yarn cache
      id: yarn-cache-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Cardhost test suite
      run: yarn test:ember
      working-directory: cardhost

  server_tests:
    name: "Server tests"
    runs-on: ubuntu-latest
    steps:
    - uses: rwjblue/setup-volta@v1
      with:
        node-version: '14'
    - name: "Global yarn"
      run: volta install yarn
    - name: Find yarn cache
      id: yarn-cache-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Server test suite
      run: yarn test
      working-directory: server

