name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set up build cache (yarn)
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-${{ hashFiles('/**/yarn.lock') }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start prereqs
      run: |
        docker network create cardstack
        docker run -d --rm --network cardstack -p 5444:5432 --name postgres cardstack/pg-test
        docker run -d --rm --network cardstack -p 8838:80 --name git-http cardstack/git-http-server;
    - name: yarn install
      run: yarn install
    - name: Linting
      run: |
        yarn lint:deps
        yarn lint:js
    - name: Node tests
      run: yarn node-tests
      env:
        PGHOST: localhost
        PGPORT: 5444
        PGUSER: postgres
    - name: Ember tests with percy
      if: github.event_name == 'pull_request'
      run: yarn ember-tests
      env:
        CI: true
        PGHOST: localhost
        PGPORT: 5444
        PGUSER: postgres
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    - name: Ember tests without percy
      if: github.event_name != 'pull_request'
      run: yarn ember-tests
      env:
        PGHOST: localhost
        PGPORT: 5444
        PGUSER: postgres
