name: CI [did-resolver]

on:
  pull_request:
    paths:
      - "packages/did-resolver/**"
      - "packages/python-did-resolver/**"
      - "packages/test-support/**"
      - "packages/eslint-config/**"
      - ".github/workflows/pr-did-resolver.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - name: Set up node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/ember-helpers/*/node_modules
            packages/firebase-functions/*/functions/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: yarn --prefer-offline --frozen-lockfile
      - run: yarn test:did-resolver
